name: ZoneRadar
packages:
  MSAL:
    url: https://github.com/AzureAD/microsoft-authentication-library-for-objc
    from: "1.6.1"
targets:
  ZoneRadar:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - ForexZoneApp
    dependencies:
      - package: MSAL
    info:
      path: ForexZoneApp/Info.plist
      properties:
        UIBackgroundModes:
          - fetch
        BGTaskSchedulerPermittedIdentifiers:
          - com.zoneradar.app.zone-refresh
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
        CFBundleDisplayName: ZoneRadar
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - msauth.com.zoneradar.app
        LSApplicationQueriesSchemes:
          - msauthv2
          - msauthv3
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zoneradar.app
        DEVELOPMENT_TEAM: DB6KZV9782
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.0"
    entitlements:
      path: ForexZoneApp/ZoneRadar.entitlements
      properties:
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.microsoft.adalcache
