using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;
using GeriRemenyi.Oanda.V20.Client.Model;
using Newtonsoft.Json;

namespace ZoneAnalyzer.PatternAnalysis.Test
{
    /// <summary>
    ///  Class for testing ZoneManager
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ZoneManagerTests : IDisposable
    {
        private ZoneManager instance;

        public ZoneManagerTests()
        {
            string serializedCandlesticks = File.ReadAllText("C:\\Enlistments\\forex-zone-analyzer\\src\\ZoneAnalyzer.PatternAnalysis.Test\\SampleCandleSticks.json");
            IEnumerable<Candlestick> candlesticks = (IEnumerable<Candlestick>)JsonConvert.DeserializeObject(serializedCandlesticks,typeof(IEnumerable<Candlestick>));
            instance = ZoneManager.Create(candlesticks);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstrumentApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' InstrumentApi
            //Assert.IsType(typeof(InstrumentApi), instance, "instance is a InstrumentApi");
        }


        /// <summary>
        /// Test GetInstrumentCandles
        /// </summary>
        [Fact]
        public void GetSupplyZonesTest()
        {
            Assert.NotNull(instance.GetSupplyZones());
            // TODO uncomment below to test the method and replace null with proper value
            //InstrumentName instrument = null;
            //DateTimeFormat? acceptDatetimeFormat = null;
            //string price = null;
            //CandlestickGranularity? granularity = null;
            //int? count = null;
            //string from = null;
            //string to = null;
            //bool? smooth = null;
            //bool? includeFirst = null;
            //int? dailyAlignment = null;
            //string alignmentTimezone = null;
            //string weeklyAlignment = null;
            //var response = instance.GetInstrumentCandles(instrument, acceptDatetimeFormat, price, granularity, count, from, to, smooth, includeFirst, dailyAlignment, alignmentTimezone, weeklyAlignment);
            //Assert.IsType<CandlesResponse> (response, "response is CandlesResponse");
        }

        /// <summary>
        /// Test GetInstrumentOrderBook
        /// </summary>
        [Fact]
        public void GetInstrumentOrderBookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InstrumentName instrument = null;
            //DateTimeFormat? acceptDatetimeFormat = null;
            //string time = null;
            //var response = instance.GetInstrumentOrderBook(instrument, acceptDatetimeFormat, time);
            //Assert.IsType<InstrumentOrderBookResponse> (response, "response is InstrumentOrderBookResponse");
        }

        /// <summary>
        /// Test GetInstrumentPositionBook
        /// </summary>
        [Fact]
        public void GetInstrumentPositionBookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InstrumentName instrument = null;
            //DateTimeFormat? acceptDatetimeFormat = null;
            //string time = null;
            //var response = instance.GetInstrumentPositionBook(instrument, acceptDatetimeFormat, time);
            //Assert.IsType<InstrumentPositionBookResponse> (response, "response is InstrumentPositionBookResponse");
        }

    }

}
