/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace GeriRemenyi.Oanda.V20.Client.Model
{
    /// <summary>
    /// The type of the candlesticks.
    /// </summary>
    /// <value>The type of the candlesticks.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum CandlestickType
    {
        /// <summary>
        /// Enum S5 for value: S5
        /// </summary>
        [EnumMember(Value = "Bid")]
        Bid = 1,

        /// <summary>
        /// Enum S10 for value: S10
        /// </summary>
        [EnumMember(Value = "Mid")]
        Mid = 2,

        /// <summary>
        /// Enum S15 for value: S15
        /// </summary>
        [EnumMember(Value = "Ask")]
        Ask = 3
    }
}
